# Generated by Django 5.0.4 on 2024-04-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('fullname', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('attend', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='students_detials',
            fields=[
                ('fullname', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('mst_1_marks', models.IntegerField(blank=True, null=True)),
                ('mst_2_marks', models.IntegerField(blank=True, null=True)),
                ('assignment_1_marks', models.IntegerField(blank=True, null=True)),
                ('assignment_2_marks', models.IntegerField(blank=True, null=True)),
                ('assignment_3_marks', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='student/images')),
            ],
        ),
    ]
