# Generated by Django 5.0.4 on 2024-04-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_detials',
            name='image',
            field=models.ImageField(upload_to='media/images'),
        ),
    ]
