# Generated by Django 5.0.4 on 2024-04-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_alter_students_detials_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_detials',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
