# Generated by Django 5.0.4 on 2024-04-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_students_detials_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
