from django.db import models

# Create your models here.
class admin_details(models.Model):
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=30)

class teacher_details(models.Model):
    fullname = models.CharField(max_length=100)
    email = models.EmailField(max_length=100,primary_key=True)
    address = models.CharField(max_length=255)
    phone = models.IntegerField()
    status = models.CharField(max_length=100,default="active")
    subject = models.CharField(max_length=100,default="Not Alloted")
    password = models.CharField(max_length=30,default="Password123")


class btech_cse_time_table(models.Model):
    day = models.CharField(max_length=100)
    time1 = models.CharField(max_length=100)
    time2 = models.CharField(max_length=100)
    time3 = models.CharField(max_length=100)
    time4 = models.CharField(max_length=100)
    time5 = models.CharField(max_length=100)
    monday = models.CharField(max_length=100)
    tuesday = models.CharField(max_length=100)
    wednesday = models.CharField(max_length=100)
    thursday = models.CharField(max_length=100)
    friday = models.CharField(max_length=100)
    subject1= models.CharField(max_length=100)
    subject2= models.CharField(max_length=100)
    subject3= models.CharField(max_length=100)
    subject4= models.CharField(max_length=100)
    subject5= models.CharField(max_length=100)
    subject6 = models.CharField(max_length=100)
    subject7 = models.CharField(max_length=100)
    subject8 = models.CharField(max_length=100)
    subject9 = models.CharField(max_length=100)
    subject10 = models.CharField(max_length=100)
    subject11 = models.CharField(max_length=100)
    subject12 = models.CharField(max_length=100)
    subject13 = models.CharField(max_length=100)
    subject14 = models.CharField(max_length=100)
    subject15 = models.CharField(max_length=100)
    subject16 = models.CharField(max_length=100)
    subject17 = models.CharField(max_length=100)
    subject18 = models.CharField(max_length=100)
    subject19 = models.CharField(max_length=100)
    subject20 = models.CharField(max_length=100)
    subject21 = models.CharField(max_length=100)
    subject22 = models.CharField(max_length=100)
    subject23 = models.CharField(max_length=100)
    subject24 = models.CharField(max_length=100)
    subject25 = models.CharField(max_length=100)